gui:
  nerdFontsVersion: "3" # showIcons is depricated
  showBottomLine: true # Line with shortcuts
  theme: # colors can be either like blue, or '#0fa332'
    lightTheme: false # For terminals with a light background
    activeBorderColor:
      - blue
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - blue
    unstagedChangesColor:
      - red
git:
  parseEmoji: true # Emojis in commits, false by default
