[colors.bright]
black = "#bbbbbb"
blue = "#5BCEFF"
cyan = "#78FFFF"
green = "#5FD24B"
magenta = "#B66CFF"
red = "#FF6D59"
white = "#ffffff"
yellow = "#FFB800"

[colors.dim]
black = "#141414"
blue = "#041824"
cyan = "#0A3535"
green = "#11230E"
magenta = "#281641"
red = "#31100D"
white = "#333333"
yellow = "#1E1200"

[colors.normal]
black = "#474747"
blue = "#1BABFF"
cyan = "#2ADEDE"
green = "#54A746"
magenta = "#955AE7"
red = "#F44336"
white = "#FFFFFF"
yellow = "#FF9800"

[colors.primary]
background = "#070707"
foreground = "#ffffff"

[colors.search.focused_match]
background = "#2adede"
foreground = "#000000"

[colors.search.matches]
background = "#ff9800"
foreground = "#000000"

[font]
size = 11.5

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "Up"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "Down"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[74;5u"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[75;5u"
key = "K"
mods = "Control|Shift"

[window]
decorations = "none"
dynamic_padding = true
title = "get me out"

[window.dimensions]
columns = 136
lines = 36

[window.padding]
x = 0
y = 0
