# Custom keymaps go here
# See more here https://github.com/aome510/spotify-player/blob/master/docs/config.md#keymaps
# See the defaults here https://github.com/aome510/spotify-player/blob/master/README.md#commands

[[keymaps]]
command = "VolumeUp"
key_sequence = "="
[[keymaps]]
command = "SeekForward"
key_sequence = "l"
[[keymaps]]
command = "SeekBackward"
key_sequence = "h"
[[keymaps]]
command = "NextTrack"
key_sequence = "C-l"
[[keymaps]]
command = "PreviousTrack"
key_sequence = "C-h"
